# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: 
      - master
      - issue-01

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

  # SSH test job
  remote:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install ssh-agent
        env:
          _ssh_secret_key: ${{ secrets._SSH_SECRET_KEY }}
          _ssh_host: ${{ secrets._SSH_HOST }} 
          _ssh_user: ${{ secrets._SSH_USER }} 
        run: |
          which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
          eval $(ssh-agent -s)
          echo "$_ssh_secret_key" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

      - name: Test ssh
        run: ssh ${{ secrets._SSH_USER }}@${{ secrets._SSH_HOST }} hostname
